version: "3.2"

services:
  oracle:
    image: daerepository03.eur.ad.sag:4443/ccdevops/oracle:11.1
    environment: 
      - ORACLE_ALLOW_REMOTE=true

  is1:
    image: daerepository03.eur.ad.sag:4443/ccdevops/commandcentral:10.2-node
    ports:
      - target: 5555

  is2:
    image: daerepository03.eur.ad.sag:4443/ccdevops/commandcentral:10.2-node
    ports:
      - target: 5555

  init: # init container
    image: daerepository03.eur.ad.sag:4443/ccdevops/commandcentral:10.2-internal
    volumes: 
      - ../../clients/docker.properties:/root/.sag/cc.properties
      - ../../environments/:/usr/share/sagcc/init/environments/
    environment: 
      - CC_SERVER=cc
      - CC_ENV=dev   
    command:
      antcc waitnodes oracledb -Dnodes=is1:sagiscluster_is1_1,is2:sagiscluster_is2_1
    depends_on: 
      - oracle
      - is1
      - is2

networks: 
  default:
    external:
      name: sagdevopstemplates_default
