sudo: required

services:
  - docker

env:
  global:
    - CC_TAG=10.3
    - CC_REG=softwareag
    - REG=sergeipogrebnyak
  matrix:
#    - CC_TEMPLATE=sag-um-server  TAG=10.1
    - CC_TEMPLATE=sag-msc-server TAG=10.1

before_install:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - cd infrastructure
  - docker-compose build
  - cd ..

script: 
  - echo "Testing $CC_TEMPLATE with release $TAG
  - ./provisionw $CC_TEMPLATE
