sudo: required

services:
  - docker

env:
  global:
    - CC_TAG=10.3
    - TAG=10.3
    - FIXES=ALL
  # matrix:
  #   - C=hello-world
  #   - C=integration-server
  #   - C=universal-messaging

before_install:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - cd infrastructure
  - docker-compose -f docker-compose.yml -f master.yml -f ${TAG}.master.yml build
  - cd ..

script: 
  - cd containers
  - docker-compose build hello-world universal-messaging integration-server
  - cd ../deployments/docker
  - docker-compose -f sag-cc/docker-compose.yml up -d
  - docker-compose -f sag-um-is-push/docker-compose.yml run --rm init
