sudo: required

services:
  - docker

env:
  global:
    - CC_TAG=10.3
    - TAG=10.3
    - FIXES=ALL
  # matrix:
  #   - C=hello-world
  #   - C=integration-server
  #   - C=universal-messaging

before_install:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - cd licenses && openssl aes-256-cbc -K $encrypted_9d8aedf6ae71_key -iv $encrypted_9d8aedf6ae71_iv -in licenses.zip.enc -out licenses.zip -d && cd ..
  - cd infrastructure && docker-compose -f docker-compose.yml:master.yml:${TAG}.master.yml build && cd ..

script: 
  - cd containers
  - docker-compose build hello-world
  - docker-compose build universal-messaging integration-server
  - cd ../deployments/docker
  - docker-compose -f sag-cc/docker-compose.yml up -d
  - docker-compose -f sag-um-is-push/docker-compose.yml run --rm init
