sudo: required

services:
  - docker

env:
  - COMPOSE_FILE=test.yml
  - TEMPLATE=jenkins

before_install:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker-compose pull

script:
  - docker-compose run --rm init1
#  - docker-compose run --rm test

# after_success:
#   - if [ "$TRAVIS_BRANCH" == "master" ]; then
#     docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
#     docker push USER/REPO;
#     fi
