version: "3.2"

services:
  cc:
    image: daerepository03.eur.ad.sag:4443/ccdevops/commandcentral:10.2-internal
    ports:
      - target: 8090 # CCE
      - target: 8091 # CCE
      - target: 8092 # SPM      
    volumes: 
      - ./templates/:/usr/share/sagcc/init/library/templates/
    environment:
      - SAG_AQUARIUS

  initcc: # wait for CC init
    image: daerepository03.eur.ad.sag:4443/ccdevops/commandcentral:10.2-internal
    volumes: 
      - ./clients/docker.properties:/root/.sag/cc.properties
      - ./environments/:/usr/share/sagcc/init/environments/
    environment: 
      - CC_SERVER=cc
      - CC_ENV
    command: >
      bash -c "sagcc list repository products -e 10.2 -w 600 --wait-for-cc 300 &&
               sagcc list repository fixes -e GA_Fix_Repo -w 600"
    depends_on: 
      - cc

  test:
    image: daerepository03.eur.ad.sag:4443/ccdevops/commandcentral:10.2-internal
    volumes: 
      - ./clients/docker.properties:/root/.sag/cc.properties
      - ./:/usr/share/sagcc/init/
    environment: 
      - CC_SERVER=cc
      - CC_TEMPLATE
      - SAG_AQUARIUS
      - EMPOWER_USR
      - EMPOWER_PSW
    command: antcc apply test -Dbuild.dir=/tmp
