version: "3.2"

services:
  cc: # CC builder service for image builds
    image: ${CC_BUILDER_IMAGE}:${CC_TAG}
    ports:
      - 8091 # CCE
    build:
      context: .
      args:
        - BASE_IMAGE=${CC_SERVER_IMAGE}:${CC_TAG}    
        - CC_INSTALLER
        - CC_INSTALLER_URL
        - LICENSES_URL
        - REPO_HOST
        - REPO_PRODUCT
        - REPO_FIX
    environment:
      - LICENSES_URL
      - REPO_HOST
      - REPO_PRODUCT
      - REPO_FIX
    volumes: 
      - ./templates/:/opt/sagtools/profiles/CCE/data/templates/composite/
      - ./scripts/init.sh:/opt/sagtools/init.sh
      #- ./scripts/inventory.sh:/opt/sagtools/inventory.sh
      #- ./scripts/provision.sh:/opt/sagtools/provision.sh

  sagcc:
    image: ${CC_CLIENT_IMAGE}:${CC_TAG}-alpine
    volumes: 
      - ./:/src/
    environment: 
      - CC_SERVER
      - CC_PASSWORD
    entrypoint: sagcc
    command: --help

  sagccant:
    image: ${CC_CLIENT_IMAGE}:${CC_TAG}
    volumes: 
      - ./:/src/
    environment: 
      - CC_SERVER
      - CC_PASSWORD
    entrypoint: sagccant
    command: -p

  apply:
    image: ${CC_CLIENT_IMAGE}:${CC_TAG}-alpine
    volumes: 
      - ./:/src/
    environment: 
      - CC_SERVER
      - CC_PASSWORD
      - CC_WAIT
      - CC_CHECK_EVERY=10
    entrypoint: sagcc exec templates composite apply --sync-job
    command: --help

  # test:
  #   # FIXME: use client image with antcc
  #   image: ${DOCKER_REGISTRY_URL}/${ORG}/commandcentral:${RELEASE}-internal
  #   volumes: 
  #     - ./clients/docker.properties:/root/.sag/cc.properties
  #     - ./:/usr/share/sagcc/init/
  #   environment: 
  #     - CC_SERVER=cc
  #     - CC_TEMPLATE
  #     - SAG_AQUARIUS
  #     - EMPOWER_USR
  #     - EMPOWER_PSW
  #   command: antcc templateApply templateTest -Dbuild.dir=/tmp

  # default provisioner
  provision:
    image: daerepository03.eur.ad.sag:4443/ccdevops/commandcentral-builder:10.3
    entrypoint: /opt/sagtools/provision.sh
    volumes: 
      - ./templates/:/opt/sagtools/profiles/CCE/data/templates/composite/
      - ./scripts/inventory.sh:/opt/sagtools/inventory.sh
      - ./scripts/provision.sh:/opt/sagtools/provision.sh

  # # default builder
  # node:
  #   # image: annonymous
  #   build:
  #     context: .
  #   environment:
  #     - CC_AUTO_REGISTER=0              # No auto register as we don't have a server
