version: "3.2"

services:
  provision:
    image: daerepository03.eur.ad.sag:4443/ccdevops/commandcentral-builder:10.3
    entrypoint: /opt/sagtools/provision.sh
    volumes: 
      - ./:/src/ # required
