version: "3.2"

services:
  sqlserver:
    image: microsoft/mssql-server-linux:2017-latest
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MaNaGe123

  tc02:
    image: daerepository03.eur.ad.sag:4443/ccdevops/terracotta-server:10.3
    ports:
      - 9010:9010                       
      - 9030:9030                       
      - 9040:9040                       
      - 8092                       
    hostname: tc02
    environment:
      - CC_AUTO_REGISTER=1              
      - OFFHEAP_MAX_SIZE=513m

  um02:
    image: daerepository03.eur.ad.sag:4443/ccdevops/universal-messaging:10.3
    ports:
      - 9000:9000
      - 8092
    hostname: um02
    environment:
      - CC_AUTO_REGISTER=1

  is02:
    image: daerepository03.eur.ad.sag:4443/ccdevops/integration-server:10.3
    hostname: is02
    ports:
      - 5555:5555
      - 8092
    environment:
      - CC_AUTO_REGISTER=1     
    depends_on: 
      - sqlserver
      - tc02
      - um02
      - initdb

  initdb:
    image: daerepository03.eur.ad.sag:4443/ccdevops/commandcentral-client:10.3
    environment: 
      - CC_SERVER=cc
      - CC_PASSWORD
      - CC_CHECK_EVERY=10
    command: >
      sagcc exec templates composite apply sag-db-sqlserver 
        repo.product=products repo.fix=fixes
        release=10.3 nodes=node db.host=sqlserver db.admin.password=MaNaGe123 db.products=[IS] --wait-for-cc --wait 600 --sync-job
    depends_on: 
      - sqlserver

networks:
  default:
    external:
      name: sag-cc_default
