version: "3.2"

services:
  node: # built image with the tested template
    image: ${TARGET_IMAGE}:${TAG}
    build:
      context: .
      args:
        - BUILDER_IMAGE=${CC_BUILDER_IMAGE}:${CC_TAG}-${TAG}
        - BASE_IMAGE=${CC_NODE_IMAGE}:${CC_TAG}
        # - __exx_broker_fixes=[] # control fix list
        # - __exx_broker_tcp_port=1971
    hostname: node
    ports:
      - "1971"
      - "8092"
    environment:
      - CC_AUTO_REGISTER=0 # auto register with Builder server
    # volumes:
      # JUST for debugging
      # - ./entrypoint.sh:/opt/softwareag/entrypoint.sh

  test: # 
    image: ${CC_CLIENT_IMAGE}:${CC_TAG}
    environment:
      - CC_SERVER=http://node:8092/spm # point to SPM
    links:
      - node
    command: > 
      bash -c '
      echo "Verifying container ..." &&
      sagcc list inventory products -e EntireXBroker --wait-for-cc &&
      sagcc list inventory components -e ETB4711'
      # '&&
      # echo "Waiting for runtime status ..." &&
      # sagcc list monitoring state Broker??? -e ONLINE
      # '
