version: "3.2"

services:
  # provisioner
  provision:
    image: daerepository03.eur.ad.sag:4443/ccdevops/commandcentral-builder:$TAG
    entrypoint: bash -c '/opt/sagtools/provision.sh && ./test.sh'
    volumes: 
      - ./:/src/ # required
    environment:
      - __tc_data_dir=/data   # template specific param
