version: "3.2"

services:
  # provisioner
  provision:
    image: daerepository03.eur.ad.sag:4443/ccdevops/commandcentral-builder:10.3
    entrypoint: bash -c '/opt/sagtools/provision.sh && ./test.sh'
    volumes: 
      - ./:/src/ # required
    environment:
        # hello.name parameter is passed in as '__hello_name'
      - __hello_world=VM                # template test specific param
      - HELLO_NAME=VM_INSTANCE          # runtime specific ENV var

  # target container
  node:
    image: daerepository03.eur.ad.sag:4443/ccdevops/helloworld # target image
    build:
      context: .
      dockerfile: Dockerfile            # instructions to build image
      args:
        # hello.name parameter is passed in as '__hello_name'
        - __hello_world=Container       # container specific build ARG
    ports:
      - "8092"                          # container specific ports
    environment:
      - CC_AUTO_REGISTER=0              # No auto register as we don't have a server
      - HELLO_NAME=CONTAINER_INSTANCE   # container specific ENV var
    volumes:
      - ./entrypoint.sh:/opt/softwareag/entrypoint.sh # for dev only to avoid image rebuild

  # test container
  test:
    image: daerepository03.eur.ad.sag:4443/ccdevops/commandcentral-client:10.3
    environment:
      - CC_SERVER=http://node:8092/spm # if node is a managed image, point to its SPM
      - NODES=                         # empty because we're tring against SPM itself
    volumes:
      - ./:/src/                       # provide access to test.sh
    command: /src/test.sh              # run the tests
