version: "3.2"

services:
  um:
    image: ${DOCKER_REGISTRY_URL}/${ORG}/universal-messaging:${TAG}
    build:
      context: .
      args:
        - BUILDER_IMAGE=${DOCKER_REGISTRY_URL}/${ORG}/commandcentral-builder:${TAG}-internal
        - BASE_IMAGE=${DOCKER_REGISTRY_URL}/${ORG}/commandcentral-node:${TAG}
    hostname: um
    ports:
      - "9000"
    environment:
      - CC_SERVER=builder

  test:
    image: ${DOCKER_REGISTRY_URL}/${ORG}/commandcentral-client:${TAG}
    environment:
      - CC_SERVER=builder    
    links:
      - um
    command: >
      bash -c '
      echo "Checking managed container status ..." &&
      sagcc list monitoring state um -e ONLINE -w 600 --wait-for-cc
      '

networks: 
  default:
    external:
      #name: sagdevops-templates_default
      name: sagdevopstemplates_default

