version: "3.2"

services:
  um:
    image: daerepository03.eur.ad.sag:4443/ccdevops/commandcentral:10.2-node
    ports:
      - target: 9000
    environment:
      - CC_AUTO_REGISTER=0
      
  init: # init container
    image: daerepository03.eur.ad.sag:4443/ccdevops/commandcentral:10.2-internal
    volumes: 
      - ../../clients/docker.properties:/root/.sag/cc.properties
      - ../../environments/:/usr/share/sagcc/init/environments/
    environment: 
      - CC_SERVER=cc
      - CC_ENV   
    command:
      antcc waitnodes -Dnodes=um
    depends_on: 
      - um

networks: 
  default:
    external:
      name: sagdevopstemplates_default
