version: "3.2"

services:
  um:
    image: daerepository03.eur.ad.sag:4443/ccdevops/commandcentral:10.2-node
    ports:
      - target: 9000
    environment:
      - CC_AUTO_REGISTER=0

  init: # init container
    image: daerepository03.eur.ad.sag:4443/ccdevops/commandcentral:10.2-internal
    volumes: 
      - ../../clients/docker.properties:/root/.sag/cc.properties
      - ../../environments/:/usr/share/sagcc/init/environments/
      - ../../templates/:/usr/share/sagcc/init/templates/
    environment: 
      - CC_SERVER=cc
      - CC_ENV
      - SAG_AQUARIUS
    command:
      antcc templates sagenv.up waitnodes -Dnodes=um
    depends_on: 
      - um

  builder: # builder container
    image: daerepository03.eur.ad.sag:4443/ccdevops/commandcentral:10.2-internal
    volumes: 
      - ../../clients/docker.properties:/root/.sag/cc.properties
      - ./:/usr/share/sagcc/builder
    environment: 
      - CC_SERVER=cc
      - CC_ENV 
    working_dir: /usr/share/sagcc/builder
    command: antcc validate -Denv.properties=init.properties

networks: 
  default:
    external:
      name: sagdevopstemplates_default
