version: "3.2"

services:
  um:
    image: ${DOCKER_REGISTRY_URL}/${ORG}/universal-messaging:${TAG}
    build:
      context: .
      args:
        - BUILDER_IMAGE=${DOCKER_REGISTRY_URL}/${ORG}/builder:${RELEASE}-dev
        - BASE_IMAGE=${DOCKER_REGISTRY_URL}/${ORG}/node:${RELEASE}
    ports:
      - "9000"
    environment:
      - CC_SERVER=cc
    volumes: 
      - ../../build/run/data/um1:/opt/softwareag/UniversalMessaging/server/default/data/

networks: 
  default:
    external:
      name: sagdevops-templates_default
