version: "3.2"

networks: 
  default:
    external:
      name: sagdevopstemplates_default

services:
  um:
    image: ${DOCKER_REGISTRY_URL}/${ORG}/universal-messaging:${TAG}
    build:
      context: .
      args:
        - BUILDER_IMAGE=${DOCKER_REGISTRY_URL}/${ORG}/commandcentral-builder:${TAG}-internal
        - BASE_IMAGE=${DOCKER_REGISTRY_URL}/${ORG}/commandcentral-node:${TAG}
    hostname: um
    ports:
      - "9000"
    environment:
      - CC_SERVER=builder
    volumes: # IMPORTANT: to have a volume, otherwise UM fails to start!
      - ../../build/run/data/um1:/opt/softwareag/UniversalMessaging/server/default/data/
      # JUST for debugging
      # - ./entrypoint.sh:/opt/softwareag/entrypoint.sh

  test:
    image: ${DOCKER_REGISTRY_URL}/${ORG}/commandcentral-client:${TAG}
    environment:
      - CC_SERVER=builder    
    links:
      - um
    command: >
      bash -c '
      echo "Checking managed container status ..." &&
      sagcc list monitoring state um -e ONLINE -w 600 --wait-for-cc
      '

