version: "3.2"

services:
  um:
    image: ${DOCKER_REGISTRY_URL}/${ORG}/commandcentral-node:${TAG}
    ports:
      - target: 9000
    hostname: um

  init: # init container
    image: daerepository03.eur.ad.sag:4443/ccdevops/commandcentral:10.2-internal
    volumes: 
      - ../../clients/docker.properties:/root/.sag/cc.properties
      - ../../environments/:/usr/share/sagcc/init/environments/
      - ../../templates/:/usr/share/sagcc/init/templates/
    environment: 
      - CC_SERVER=cc
      - CC_ENV
      - SAG_AQUARIUS
    command:
      antcc templates sagenv.up waitnodes -Dnodes=um
    depends_on: 
      - um

networks: 
  default:
    external:
      name: sagdevops-templates_default
