version: "3.2"

services:
  msc:
    image: daerepository03.eur.ad.sag:4443/ccdevops/commandcentral:10.2-node
    ports:
      - target: 5555

  init: # init container
    image: daerepository03.eur.ad.sag:4443/ccdevops/commandcentral:10.2-internal
    volumes: 
      - ../../clients/docker.properties:/root/.sag/cc.properties
      - ../../environments/:/usr/share/sagcc/init/environments/
    environment: 
      - CC_SERVER=cc
      - CC_ENV   
    command:
      antcc waitnodes -Dnodes=msc_1:sagmscserver_msc_1
    depends_on: 
      - msc

networks: 
  default:
    external:
      name: sagdevopstemplates_default
