version: "3.2"

services:
  is01:
    image: daerepository03.eur.ad.sag:4443/ccdevops/integration-server:10.3
    hostname: is01
    ports:
      - 5555
      - 8092
    environment:
      - CC_AUTO_REGISTER=1              
  um01:
    image: daerepository03.eur.ad.sag:4443/ccdevops/universal-messaging:10.3
    ports:
      - 9000
      - 8092
    hostname: um01
    environment:
      - CC_AUTO_REGISTER=1

networks:
  default:
    external:
      name: sagdevops-templates_default
