version: '3'
services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - default

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - "./datasource.yml:/etc/grafana/provisioning/datasources/prom_datasource.yaml"
      - "./dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml"
      - "./prom-stack-dash.json:/var/lib/grafana/dashboards/prom-stack-dash.json"
      - "./grafana.ini:/etc/grafana/grafana.ini"
    networks:
      - default

networks:
  default:
    external:
      name: sagdevops-templates_default
